### ISSUE TITLE
Can multiple network interfaces (network cards) use the same MAC address?

### ISSUE THREAD

**Issue by hangeV** [FreeRTOS/FreeRTOS-Plus-TCP#1062]
FreeRTOS-Plus-TCP Stack.
Can multiple network interfaces (network cards) use the same MAC address?
The IP addresses of multiple network cards are not in the same network segment.

**Comment by amazonKamath** [comment]
@hangeV request you to move this post to FreeRTOS [forums](https://forums.freertos.org/). This will not only get you more insights but also help others.

**Comment by hangeV** [comment]
No need, STHM32H750 can set 4 MAC addresses
