### ISSUE TITLE
[BUG] The endpoint with the NULL address is operated in prvTCPReturnPacket_IPV4 function

### ISSUE THREAD

**Issue by XIAO-Q7** [FreeRTOS/FreeRTOS-Plus-TCP#1077]
**Describe the bug**

When a endpoint enables DHCP and sets a AUTO IP. Receiving a tcp socket packet from a non-AUTOIP network segment causes the endpoint with a null address to be operated on in the prvTCPReturnPacket_IPV4 function.

**Target**

Any

**To Reproduce**
![Plus_TCP_BUG](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/assets/62824695/281294a7-3f64-4f05-9d0c-1ddd32798084)

- Configure: An endpoint enable DHCP and set a AUTO IP

In my case, I'm running Plus TCP on an STM32 and built a TCP echo server, employing a computer as the echo client. When I send an echo frame to the server, the microcontroller runs into HardFault_Handler.

**Expected behavior**

Server correctly returns echo frames.

I have set a special IP address for the computer in this case, not the AUTOIP segment. If PLUS TCP can't automatically find an entry point to send frames. It can not send the frame. I don't want the chip to enter HardFault_Handler.

**Additional context**

Through my debugging, I found that in the prvTCPReturnPacket_IPV4 function, the line of code here gives an endpoint to a null address.

```C
eResult = eARPGetCacheEntry( &ulDestinationIPAddress, &xMACAddress, &( pxNetworkBuffer->pxEndPoint ) );
```

and later operates this endpoint with a null address to send frames, eventually causing the chip to run into HardFault_Handler.

```C
NetworkInterface_t * pxInterface = pxNetworkBuffer->pxEndPoint->pxNetworkInterface;
( void ) pxInterface->pfOutput( pxInterface, pxNetworkBuffer, xDoRelease );
```

**Comment by htibosch** [comment]
Hello @XIAO-Q7 , thanks a lot for reporting this.
I'm trying to reproduce it, and a fix is on its way.
Thanks

**Comment by tony-josi-aws** [comment]
@XIAO-Q7, we have merged #1078 that should be fixing the issue reported, if possible, please verify if the fix works for you by pulling the latest changes from main.

**Comment by XIAO-Q7** [comment]
Yes, it worked. Thank you for your help.

**Comment by tony-josi-aws** [comment]
Thanks for verifying.
