### ISSUE TITLE
[BUG] Sockets GCC array-bounds Warning

### ISSUE THREAD

**Issue by HTRamsey** [FreeRTOS/FreeRTOS-Plus-TCP#1141]
GCC 12.3
FreeRTOS_Sockets.c
Line 3047
array-bounds
![image](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/assets/68555040/615bd823-c9c7-4000-a95a-cc4b94a46ca4)

**Comment by htibosch** [comment]
Hello @HTRamsey, can you please elaborate more on what we're looking at? Are you compiling or running a program?
Does the "bug" that you have discovered cause undesired behaviour?
Which tool are you using in the screen shot? I hope it is not Eclipse?
