### ISSUE TITLE
[BUG]Missing parameters and undefined macros

### ISSUE THREAD

**Issue by lightning51522** [FreeRTOS/FreeRTOS-Plus-TCP#1190]
I am currently porting TCP packets of version 4.2.2 Release. On ATSAM4E, I have found issues with missing parameters when calling functions in the network interface source file, as well as the use of an undefined macro。

1.The function `usGeneratedProtocolChecksum` called in line 422 of the `portable/NetworkInterface/ATSAM4E/NetworkInterface. c` file is missing a length parameter.
2.The macro `ipLOCAL_MAC_ADDRESS` used on line 315 of the same file has not been defined.

Hope these errors can be fixed

**Comment by kar-rahul-aws** [comment]
Hi @lightning51522 
I have raised a PR for fixing the missing parameter issue in ATSAM4E port. Thanks for pointing out the issue. 
Regarding your other concern, [DriverSAM ](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/tree/main/source/portable/NetworkInterface/DriverSAM) replaces the older ATSAM4E port. So, you can use this port in your project . 
You can take a look at this [PR](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/pull/957) , and make similar changes to the ATSAM4E port and raise a PR. We will be happy to review it. 

Thanks.

**Comment by jasonpcarroll** [comment]
Can this issue be closed?

**Comment by kar-rahul-aws** [comment]
Closing this issue since the [PR] (https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/pull/1192) has been merged. Please reopen this issue if you feel otherwise.
