### ISSUE TITLE
possiblity for static creation of IP task, queues, etc.

### ISSUE THREAD

**Issue by tajen** [FreeRTOS/FreeRTOS-Plus-TCP#208]
When configSUPPORT_STATIC_ALLOCATION is 1, idleTask and others are statically created, +TCP should also honor this as well.

**Comment by AniruddhaKanhere** [comment]
Hello @tajen, Thanks for bringing this to our attention, and apologies for the late reply.
We will work on this and create a PR. If you would like, you can go ahead and create the PR which we shall help you with.

**Comment by tajen** [comment]
I may need it for my project. If so, I will create a PR

**Comment by archigup** [comment]
As this is being tracked in PR https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/pull/217, I am closing this issue. Thanks!
