### ISSUE TITLE
Possible overflow in xProcessReceivedTCPPacket

### ISSUE THREAD

**Issue by bernd-edlinger** [FreeRTOS/FreeRTOS-Plus-TCP#216]
This check looks as if has an issue if ulCurrentSequenceNumber + ulRxWindowLength overflows:

https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/blob/d6ed4473d3e1eedde57d0abf6b93992ce4f85d3a/FreeRTOS_TCP_IP.c#L3586-L3588

**Comment by AniruddhaKanhere** [comment]
Hello @bernd-edlinger, thanks for bringing this to our notice.  We'll look into this and report back shortly.

**Comment by htibosch** [comment]
I just prepared a [PR #225](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/pull/225) with the title "Before sending a challenge ACK, check the sequence number more properly".
It is using the sequence number routines that are defined in [FreeRTOS_TCP_WIN.c](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/blob/bfa155920ed37302ea4799728795eec2298e696c/FreeRTOS_TCP_WIN.c#L249).

@bernd-edlinger, : thanks a lot for reporting this. You can not close this issue.

**Comment by bernd-edlinger** [comment]
Fixed with commit e88ecd3.
Thanks!
