### ISSUE TITLE
Possible error in function prvTCPWindowFastRetransmit

### ISSUE THREAD

**Issue by SL-RU** [FreeRTOS/FreeRTOS-Plus-TCP#345]
I'm using FreeRTOS+TCP V2.3.4 and FreeRTOS Kernel V10.4.5. I've  found that GCC embed static analyzer detected such possible  error. I didn't give it a deep dive in but I've got hard fault once accidentally in that place randomly once.

Here is output of gcc linker with flags `-fanalyzer -fuse-linker-plugin -flto -ffat-lto-objects ...` and gcc compiler `-flto ...`:

```
FreeRTOS/FreeRTOS-Plus-TCP/portable/BufferManagement/BufferAllocation_1.c: In function 'uxListRemove':
FreeRTOS/FreeRTOS-Kernel/list.c:211:13: warning: dereference of NULL 'pxList_11' [CWE-476] [-Wanalyzer-null-dereference]
  211 |     ( pxList->uxNumberOfItems )--;
      |             ^
  'prvTCPWindowFastRetransmit': events 1-4
    |
    |FreeRTOS/FreeRTOS-Plus-TCP/FreeRTOS_TCP_WIN.c:1968:25:
    | 1968 |         static uint32_t prvTCPWindowFastRetransmit( TCPWindow_t * pxWindow,
    |      |                         ^
    |      |                         |
    |      |                         (1) entry to 'prvTCPWindowFastRetransmit'
    |......
    | 1983 |             while( pxIterator != pxEnd )
    |      |                               ~
    |      |                               |
    |      |                               (2) following 'true' branch (when 'pxIterator_14 != pxEnd_18')...
    |......
    | 1986 |                 pxSegment = ipCAST_PTR_TO_TYPE_PTR( TCPSegment_t, listGET_LIST_ITEM_OWNER( pxIterator ) );
    |      |                 ~        
    |      |                 |
    |      |                 (3) ...to here
    |......
    | 2016 |                             ( void ) uxListRemove( &pxSegment->xQueueItem );
    |      |                                      ~
    |      |                                      |
    |      |                                      (4) calling 'uxListRemove' from 'prvTCPWindowFastRetransmit'
    |
    +--> 'uxListRemove': events 5-9
           |
           |FreeRTOS/FreeRTOS-Kernel/list.c:188:13:
           |  188 | UBaseType_t uxListRemove( ListItem_t * const pxItemToRemove )
           |      |             ^
           |      |             |
           |      |             (5) entry to 'uxListRemove'
           |......
           |  210 |     pxItemToRemove->pxContainer = NULL;
           |      |                                 ~
           |      |                                 |
           |      |                                 (6) 'pxList_11' is NULL
           |      |                                 (7) 'pxList_11' is NULL
           |      |                                 (8) 'pxList_11' is NULL
           |  211 |     ( pxList->uxNumberOfItems )--;
           |      |             ~
           |      |             |
           |      |             (9) dereference of NULL 'pxList_11'
           |

```

**Comment by dachalco** [comment]
@SL-RU 

This is great feedback. @AniruddhaKanhere could you review this?

**Comment by AniruddhaKanhere** [comment]
@SL-RU, if I understand this correctly, then the static analysis is showing that at line 210 in list.c this statement is present: `pxItemToRemove->pxContainer = NULL;` and then somehow it deduces that the next statement at line 211 (`( pxList->uxNumberOfItems )--;`) is dereferencing NULL?

I am not sure I understand the logic behind this. Does the static checker somehow is thinking that the statement at line 192 (`List_t * const pxList = pxItemToRemove->pxContainer;`) in conjecture with line 210 in list.c (`pxItemToRemove->pxContainer = NULL;`) makes the value of pxList NULL? If so, then we can safely mark this as a false positive.

Did I understand this right?

**Comment by SL-RU** [comment]
> If so, then we can safely mark this as a false positive. 
> Did I understand this right?

Yeah it seems so. I should have looked more closely at the report, it is just false positive. Thank you for the participation!

**Comment by AniruddhaKanhere** [comment]
@SL-RU, thanks.
Feel free to re-open this issue or create a new one if you have any more questions/concerns/issues.

I'll close the issue now.

Thanks,
Aniruddha

**Comment by htibosch** [comment]
Maybe it is worth mentioning that there is also the [FreeRTOS forum](https://forums.freertos.org), where you can ask any question about FreeRTOS or its libraries.
Many experts are monitoring the forum daily, and give quick and adequate answers.
