### ISSUE TITLE
FreeRTOS-Plus-TCP without event groups functionality to use with an older FreeRTOS?

### ISSUE THREAD

**Issue by indraneelpatil** [FreeRTOS/FreeRTOS-Plus-TCP#364]
I want to use FreeRTOS-Plus-TCP with an older freertos <v8 and event groups was introduced in v8, so I set ipconfigSUPPORT_SELECT_FUNCTION to 0 in my FreeRTOSIPConfig.h

But I just found out that FreeRTOS-Plus-TCP natively uses event groups API like xEventGroupCreate, does that mean I cannot use FreeRTOS-Plus-TCP with FreeRTOS version older than v8?

Is there any way to get this working without event groups functionality?

Thanks!

**Comment by indraneelpatil** [comment]
@htibosch  Hi Hein! thanks for your quick response and pointing me to the forum, I'll use that henceforth.

Why cant we update the FreeRTOS+TCP readme to indicate this v8.2 dependency? It may save someone in the future a lot of time?

We are using the ISIS-OBS platform https://www.isispace.nl/product/on-board-computer/ who's board support packages came with a pre-configured FreeRTOS with an older kernel and I am not sure what problems I can face with this board by upgrading the kernel. I am skeptical about the update because I could be opening a pandora's box and risk losing development time.

I am considering switching to lwip at the moment. Any brief opinion on this before we close the issue?

**Comment by htibosch** [comment]
> Any brief opinion on this before we close the issue?

Even after a subject is closed we can continue talking, here or on the forum.

It is possible that lwIP will work together with older versions of the FreeRTOS kernel. It uses semaphores and queues to synchronise access to the library.

> I am skeptical about the update because I could be opening a pandora's box and risk losing development time

Newer versions of the kernel have always been downward compatible. I maintain many projects with M4 or M7, linking them to all versions of the kernel, between v8.2 and today's V10.4.4.

At some point, a long time ago, defines were changed, but `#defines` were added to ease the pain:
~~~c
#if configENABLE_BACKWARD_COMPATIBILITY == 1
    #define eTaskStateGet                 eTaskGetState
    #define portTickType                  TickType_t
    #define xTaskHandle                   TaskHandle_t
    ...
~~~
Personally I don't see big problems when you upgrade the FreeRTOS kernel to a new release. And if you get stuck, there is always the FreeRTOS forum.
