### ISSUE TITLE
Domain name handling with out DNS cache enabled

### ISSUE THREAD

**Issue by go2sh** [FreeRTOS/FreeRTOS-Plus-TCP#390]
I downloaded the latest multi/IPv6 branch and compiled it in default configuration. The DNS code produces compilations errors:

- pcName is disabled in ParseSet_t, even needed for dns operation [here](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/blob/dbba1fad396eed22a2c418db9882eb6994d4a0a6/include/FreeRTOS_DNS.h#L139)
- prvReadNameField is disabled, even needed [here](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/blob/dbba1fad396eed22a2c418db9882eb6994d4a0a6/FreeRTOS_DNS.c#L223-226)
- ucName is disabled in freertos_addrinfo, even needed for dns operations. [here](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/blob/dbba1fad396eed22a2c418db9882eb6994d4a0a6/include/FreeRTOS_DNS.h#L94-L96)

**Comment by go2sh** [comment]
To give some more background:
- prvReadNameField is needed to parse the question and answer sections correctly
- ucName and pcName might be needed with you want to fill the ai_canonname with something independently of the cache

**Comment by abhidixi11** [comment]
Hello @go2sh , apologies for late reply. 
Can you  please point me to the code where prvReadNameField is needed but ipconfigUSE_DNS_CACHE or ipconfigDNS_USE_CALLBACKS is not set, same for ucName and pcName. Thanks.

**Comment by htibosch** [comment]
Hi @go2sh, thanks for reporting this. One additional question / request: could you attach your copy of FreeRTOSIPConfig.h to your post please?
It should be zipped and you can just drag the file from a file explorer to the edit box.
Thanks

**Comment by go2sh** [comment]
I'am back at work on monday. I'll check my code and I can also provide you my workaround.

**Comment by AniruddhaKanhere** [comment]
Hello @go2sh, any updates?

**Comment by go2sh** [comment]
See the pr #405 for the code I'am using to fix the issue.

**Comment by go2sh** [comment]
> Hi @go2sh, thanks for reporting this. One additional question / request: could you attach your copy of FreeRTOSIPConfig.h to your post please? It should be zipped and you can just drag the file from a file explorer to the edit box. Thanks

the required option in the config is just `#define ipconfigUSE_DNS_CACHE 0`

**Comment by go2sh** [comment]
In the integration branch it seams to be fixed already.

**Comment by AniruddhaKanhere** [comment]
> In the integration branch it seams to be fixed already.

Yes, that branch is not for IPv6. That branch is refactoring IPv4 source code to allow us to provide 100% test coverage and to compartmentalize the codebase.

**Comment by moninom1** [comment]
The issue was resolved long back by decoupling DNS cache from the core DNS functionality in the IPv4 main. And now the main and IPv6 branch has merged so issue seems to be resolved in both. Please feel free to reopen the issue if you still feel something is missing. Thank you for the contribution.
