### ISSUE TITLE
In STM32Fxx ethernet driver - race condition in RX check

### ISSUE THREAD

**Issue by pavel-a** [FreeRTOS/FreeRTOS-Plus-TCP#457]
[Here](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/blob/c90932edc0c740cb44c8a5aef77351108dbb00ea/portable/NetworkInterface/STM32Fxx/NetworkInterface.c#L1299)

Race condition: a bit in `ulISREvents` is cleared non-atomically in `prvEMACHandlerTask`, while it can be written by interrupt handler.
A better signaling of RX events, combined with link state check is proposed in STM32 forum [link](https://community.st.com/s/question/0D53W00001VXhtSSAT/bug-dma-fatal-error-ethernet-in-stm32f407-processor), by [@Piranha](https://community.st.com/s/profile/0050X0000088kkUQAQ) 

[quote]
Instead of using `vTaskNotifyGiveFromISR(...)` from the ISRs ....  use `xTaskNotifyFromISR(hTask, fEvents, eSetBits, &fYield)`. 

Then in the task `ulTaskNotifyTake(pdTRUE, pdMS_TO_TICKS(250))` will just return those flags and clear the internal variable without race conditions. ....  if it returns zero, then it has timed out because there are no new frames received for at least 250ms, which 
means the time has come to check (and update, if necessary) the state of physical link. 
A proper link state checking logic free of charge without additional tasks, timers or whatnot!
[/quote]

**Comment by AniruddhaKanhere** [comment]
Thanks @pavel-a for reporting the issue to us.

We have created PRs and merged suggested changes.

I will be closing this issue now.

Feel free to re-open this issue or create a new one in case you have some questions/concerns.

Thanks
