### ISSUE TITLE
[Feature Request] Function to get EMAC task handle

### ISSUE THREAD

**Issue by jonathangjertsen** [FreeRTOS/FreeRTOS-Plus-TCP#691]
**Is your feature request related to a problem? Please describe.**

I would like to get at the EMAC task handle (specifically the `_deferred_task` in the TM4C port) so I can set and get a task number, for tracing/visualization.

**Describe the solution you'd like**

A function that returns the EMAC task handle. I'm not sure if this should be a general API function or if it should just be added for the specific port I'm interested in.

**Describe alternatives you've considered**

I can't think of any other way to get this info since the variable is static.

**Additional context**

None

**Comment by n9wxu** [comment]
You could expose the variable or add a function for your tracing purposes.  Submit a PR with the change and we will review it.

**Comment by htibosch** [comment]
When your `FreeRTOSConfig.h` defines:
~~~
#define INCLUDE_xTaskGetHandle      1
~~~
you can obtain the task handle by calling:
~~~
TaskHandle_t  xHandle = xTaskGetHandle( "EMAC" );
~~~

A disadvantage of adding a new function to a network driver, is that it will only work for the TM4C-driver, unless we change all drivers.

**Comment by jonathangjertsen** [comment]
Thanks @htibosch, that will do just as well
