### ISSUE TITLE
[BUG] Cmake error due to missing CMakeLists.txt

### ISSUE THREAD

**Issue by adam-stamand** [FreeRTOS/FreeRTOS-Plus-TCP#753]
**Describe the bug**
CMakeListst.txt inside of ./test includes a subdirectory (cmbc) that doesn't have a CMakeLists.txt file.

**Host**
- Host OS: Windows 10
- Version: 10.0.19044

**To Reproduce**
- cmake ../ from build directory

**Expected behavior**
cmake runs with no errors

**Actual behavior**
```
CMake Error at test/CMakeLists.txt:4 (add_subdirectory):
  The source directory

    ./FreeRTOS-Plus-TCP/test/cbmc

  does not contain a CMakeLists.txt file.
```

**Comment by amazonKamath** [comment]
@adam-stamand  Cmake support is still  a work in progress. We recently merged a PR https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/pull/557 which introduced CMake support.  Feature request for cmake support is currently open - https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/pull/557.
