### ISSUE TITLE
[BUG] Build Error in STM32Fxx/NetworkInterface.c

### ISSUE THREAD

**Issue by holden-zenith** [FreeRTOS/FreeRTOS-Plus-TCP#767]
xMACEntry is defined here if ( ipconfigUSE_LLMNR != 0 ) || ( ipconfigUSE_MDNS != 0 ):
https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/blob/0b67e4551f31529a41e7c3f37a5c281bb1db7da6/source/portable/NetworkInterface/STM32Fxx/NetworkInterface.c#L456
but can be referenced here regardless causing a build error:
https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/blob/0b67e4551f31529a41e7c3f37a5c281bb1db7da6/source/portable/NetworkInterface/STM32Fxx/NetworkInterface.c#L576
There is also an issue regarding defining the function prvMACAddressConfig, ipconfigUSE_IPv6 should be checked too.
https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/blob/0b67e4551f31529a41e7c3f37a5c281bb1db7da6/source/portable/NetworkInterface/STM32Fxx/NetworkInterface.c#L761

**Comment by tony-josi-aws** [comment]
Hey @holden-zenith ,

#778 should fix this issue. Please feel free to reopen this if you feel otherwise.
