### ISSUE TITLE
[BUG] IPv6 Build Errors in FreeRTOS_IP_Utils.c

### ISSUE THREAD

**Issue by holden-zenith** [FreeRTOS/FreeRTOS-Plus-TCP#769]
xPacketSummary pxIPPacket_IPv6 is referenced many times in this file but is only defined in the struct if ipconfigUSE_IPv6. It is defined here: https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/blob/0b67e4551f31529a41e7c3f37a5c281bb1db7da6/source/include/FreeRTOS_IP_Private.h#L245

**Comment by moninom1** [comment]
Hey @holden-zenith,

Thank you for reporting the issue. We have this change planned when we will be doing build separation for IPv4 and IPv6. Thanks
