### ISSUE TITLE
[BUG] ipconfigUSE_DHCPv6 default definition

### ISSUE THREAD

**Issue by holden-zenith** [FreeRTOS/FreeRTOS-Plus-TCP#770]
This is only defined if ipconfigUSE_TCP but is referenced all over regardless. It really should always be defaulted to 0 here: https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/blob/0b67e4551f31529a41e7c3f37a5c281bb1db7da6/source/include/FreeRTOSIPConfigDefaults.h#L196

**Comment by moninom1** [comment]
Hey @holden-zenith,

Thank you for reporting the issue. We will add a fix for this. Thanks

**Comment by tony-josi-aws** [comment]
Hey @holden-zenith ,

Closing this issue as #778 should fix this issue. Please feel free to reopen this if you feel otherwise.
