### ISSUE TITLE
[BUG] Able to define ipconfigUSE_IPv4 & ipconfigUSE_IPv6 to 0

### ISSUE THREAD

**Issue by holden-zenith** [FreeRTOS/FreeRTOS-Plus-TCP#771]
There should be an error generated if both of these are defined to 0. https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/blob/0b67e4551f31529a41e7c3f37a5c281bb1db7da6/source/include/FreeRTOSIPConfigDefaults.h#L235

**Comment by paulbartell** [comment]
Looks like this Issue was addressed. Feel free to reopen if not.
