### ISSUE TITLE
[Feature Request] Allow more control of the DHCP discover period

### ISSUE THREAD

**Issue by bjsowa** [FreeRTOS/FreeRTOS-Plus-TCP#864]
**Is your feature request related to a problem? Please describe.**
From what I understand, the DHCP client, when no server is present, works like this:

1. Set the discover period to dhcpINITIAL_DHCP_TX_PERIOD.
2. Send DHCPDISCOVER message and wait the discover period for a reply.
3. Multiply the discover period by 2.
4. If the discover period is larger than ipconfigMAXIMUM_DISCOVER_TX_PERIOD, give up. else, go to  step 2.

In my project, I would like DHCP client to never give up, so I set :
```C
#define ipconfigMAXIMUM_DISCOVER_TX_PERIOD portMAX_DELAY
```
But the discover period quickly becomes very large and I would like it to stay on the initial value.

**Describe the solution you'd like**
A simplest solution would be to add a config option that can skip multiplying the period (skip step 3).

A more sophisticated method would be to allow defining an application function for determining the next discover period, for example:
```C
TickType_t xApplicationDHCPGetNextTxPeriod(TickType_t xCurrentTxPeriod);
```

**Describe alternatives you've considered**
I tried to use DHCP hook to change the discover period manually but the hook is only run before sending the first DHCPDISCOVER message so it would not work.

**Additional context**
Somewhat related:
https://forums.freertos.org/t/tcp-dhcp-xgivingup-and-timeouts/14531
https://forums.freertos.org/t/dhcp-never-give-up-freertos-tcp/8081/10

**Comment by kar-rahul-aws** [comment]
@bjsowa  Thanks for the feature request. We are currently looking into your request .
In the meantime, we're happy to review any contributions in the form of a Pull Request.

**Comment by kar-rahul-aws** [comment]
Hi @bjsowa 
We had an initial round of discussion regarding your feature request. The use-case suggested by you, seems to be application specific and we would like to know more on the same, what problem you are tying to solve. Can you please elaborate on this.
Thanks.

**Comment by shubnil** [comment]
Hi,
I want to add one more point here.
With the above mentioned method, the User application has the flexibility to request for DHCP IP any number of times based on the application use case.
The way to do that is to repeat the Steps 1 to 6 in a loop (finite or infinite loop based on the application use case).

This approach makes the FreeRTOS-plus-TCP stack aligned with the RFC guidelines(finite number of DHCP requests) as well as gives the application the flexibility to repeat the process based on the actual use-case requirement.

**Comment by bjsowa** [comment]
> 1. Makes the FreeRTOS-plus-TCP stack aligned with the RFC guidelines(finite number of DHCP requests)

@shubnil Can you point me to the RFC guideline about finite number of DHCP requests

> 1. User Application calls DHCP Hook

@kar-rahul-aws I'm a little bit confused about this part. From what I understand [xApplicationDHCPHook](https://www.freertos.org/FreeRTOS-Plus/FreeRTOS_Plus_TCP/API/xApplicationDHCPHook.html) is called by the FreeRTOS-Plus-TCP stack, not by the user. 

Also, does this solution allow me to prevent the discover period from increasing exponentially?

**Comment by kar-rahul-aws** [comment]
@bjsowa 
Please find the RFC guideline about finite number of DHCP requests [here](https://www.ietf.org/rfc/rfc2131.txt) [Please refer Page 23]
[xApplicationDHCPHook](https://www.freertos.org/FreeRTOS-Plus/FreeRTOS_Plus_TCP/API/xApplicationDHCPHook.html) is an application defined hook (or callback) function that is called by the FreeRTOS-Plus-TCP stack. The implementation is decided by the application, hence if the design of the callback is such that , unless the eDHCPCallbackPhase_t returns "IP obtained" , the state is kept as eDHCPContinue, effectively it means DHCP process keeps on trying to allocate an IP address, without the need to prevent the discover period from increasing exponentially.

**Comment by kar-rahul-aws** [comment]
Hi @bjsowa 
Does the previous response answer your question ?
Please let us know if any more support is needed from our end.
Thanks

**Comment by kar-rahul-aws** [comment]
Hi @bjsowa 
Closing this issue since there are no updates.
Feel free to let us know if you have any more queries.

Thanks.
