### ISSUE TITLE
Errno 11 in FreeRTOS_errno_TCP.h is used twice

### ISSUE THREAD

**Issue by dervomsee** [FreeRTOS/FreeRTOS-Plus-TCP#888]
Errno 11 is used twice: https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/blob/d7003598726cfaa4205f1a72e0546d1627d9b27e/source/include/FreeRTOS_errno_TCP.h#LL48C1-L48C1

**Comment by RichardBarry** [comment]
Thanks for taking the time t o report this, but it is intentional and as expected - search for EAGAIN on https://man7.org/linux/man-pages/man3/errno.3.html.
